Phone_Book/phone_book_crud/phone_book_app/urls.py
from django.urls import path, include
from phone_book_app import views

from .views import HomePageView, SearchResultsView

urlpatterns = [
    path('new', views.new),
    path('show',views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy, name='show'),
    path('search/', SearchResultsView.as_view(), name='show'),
]

Phone_Book/phone_book_crud/phone_book_crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phone_book_app.urls')),
]

Phone_Book/phone_book_crud/phone_book_app/models.py
from django.db import models

# Create your models here.

class Person(models.Model):

    pfirst_name = models.CharField(max_length=50)
    plast_name = models.CharField(max_length=50)
    pphone_number = models.CharField(max_length=50)
    pemail = models.EmailField()

    class Meta:
        db_table = "person"

    def __str__(self):
        return self.pfirst_name +" "+ self.plast_name +" "+ self.pphone_number +" "+ self.pemail

Phone_Book/phone_book_crud/phone_book_app/forms.py
from django import forms
from phone_book_app.models import Person

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = "__all__"

Phone_Book/phone_book_crud/phone_book_app/views.py
from django.shortcuts import render, redirect
from phone_book_app.forms import PersonForm
from phone_book_app.models import Person
from django.views.generic import TemplateView, ListView
from django.db.models import Q


# Create your views here.

def new(request):
    if request.method == "POST":
        form = PersonForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = PersonForm()
    return render(request,'index.html',{'form':form})


def show(request):
    object_list = Person.objects.all()
    return render(request,"show.html",{'object_list':object_list})


def edit(request, id):
    person = Person.objects.get(id=id)
    return render(request,'edit.html', {'person':person})


def update(request, id):
    person = Person.objects.get(id=id)
    form = PersonForm(request.POST, instance = person)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'person': person})


def destroy(request, id):
    # you can delete contact if co email or phone number
    # return list of contacts
    person = Person.objects.get(id=id)

    try:
        check_mail = Person.objects.filter(pemail='').get(id=id)
        person.delete()
    except:
        pass

    try:
        chek_num_phone = Person.objects.filter(pphone_number='').get(id=id)
        person.delete()
    except:
        pass

    return redirect("/show")


class HomePageView(TemplateView):
    template_name = 'index.html'


class SearchResultsView(ListView):
    model = Person
    template_name = 'show.html'

    def get_queryset(self):
        # search by name or last name or phone number or email
        query = self.request.GET.get('q')
        object_list = Person.objects.filter(
            Q(pfirst_name__icontains=query) |
            Q(plast_name__icontains=query) |
            Q(pphone_number__icontains=query) |
            Q(pemail__icontains=query)
            )
        return object_list

Phone_Book/phone_book_crud/phone_book_app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aktualizuj dane</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{person.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Aktualizuj dane</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Imię:</label>
    <div class="col-sm-4">
        <input type="text" name="pfirst_name" id="id_pfirst_name" required maxlength="50" value="{{ person.pfirst_name }}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nazwisko:</label>
    <div class="col-sm-4">
        <input type="text" name="plast_name" id="id_plast_name" required maxlength="50" value="{{ person.plast_name }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Telefon:</label>
    <div class="col-sm-4">
        <input type="text" name="pphone_number" id="id_pphone_number" required maxlength="50" value="{{ person.pphone_number }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
        <input type="email" name="pemail" id="id_pemail" required maxlength="254" value="{{ person.pemail }}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Aktualizuj</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Phone_Book/phone_book_crud/phone_book_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Nowy kontakt</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<form method="POST" class="post-form" action="/new">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Wprowadź dane</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4">
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Imię:</label>
    <div class="col-sm-4">
      {{ form.pfirst_name }}
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">Nazwisko:</label>
    <div class="col-sm-4">
      {{ form.plast_name }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Telefon:</label>
    <div class="col-sm-4">
      {{ form.pphone_number }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Email:</label>
    <div class="col-sm-4">
      {{ form.pemail }}
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-primary">Potwierdź</button>
    </div>
  </div>
    </div>
</form>
</body>
</html>

Phone_Book/phone_book_crud/phone_book_app/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>All contacts</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<div class="container mt-3">
  <h4>Książka telefoniczna</h4>
  <br>
<body>
  <form action="{% url 'show' %}" method="get">
    <input name="q" type="text" placeholder="Search...">
  </form>
  <br>
<table class="table table-striped table-bordered table-sm">
    <thead class="thead-dark">
    <tr>
        <th>Imię</th>
        <th>Nazwisko</th>
        <th>Telefon</th>
        <th>Email</th>
        <th><a href="/new" class="btn btn-primary">Dodaj nowy kontakt</a></th>
    </tr>
    </thead>
    <tbody>
{% for person in object_list %}
    <tr>
        <td>{{ person.pfirst_name }}</td>
        <td>{{ person.plast_name }}</td>
        <td>{{ person.pphone_number }}</td>
        <td>{{ person.pemail }}</td>
        <td>
            <a href="/edit/{{ person.id }}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" >Edytuj</span></a>
            <a href="/delete/{{ person.id }}" class="btn btn-danger">Usuń</a>

        </td>
    </tr>
{% endfor %}
    </tbody>
</table>
<br>
</body>
</html>